trigger:
- master

jobs:
  - job: 'Validate'
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
      - checkout: self
      - task: UsePythonVersion@0
        displayName: "Set Python Version"
        inputs:
          versionSpec: '3.7'
          architecture: 'x64'
      - script: python3 -m venv custodian
        displayName: Setup virtual environment
      - script: source custodian/bin/activate
        displayName: Set virtual environment
      - script: pip install c7n c7n_azure
        displayName: Install custodian
      - script: pip install s3transfer==0.3.0
        displayName: Install s3transfer
      - script: custodian validate stopped-vm.yml
        displayName: Validate policy file